#!/usr/bin/perl -w

use Critic;
use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "Critic",
   ReceiveHandler => \&Receive);
$UNIVERSAL::critic = Critic->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::critic->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::critic->Execute;
